[project]
name = "e-commerce-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yug Solanki", email = "yugsolanki15@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "apache-airflow-providers-amazon>=9.35.0",
    "dbt>=2.0.0rc212",
    "dbt-postgres>=1.11.0",
]

[project.scripts]
e-commerce-analytics = "e_commerce_analytics:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
