CREATE DATABASE airflow OWNER admin;
CREATE DATABASE analytics_dev OWNER admin;

CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS staging AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS intermediate AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS curated AUTHORIZATION admin;